name: Arm32v7 Build (no wallet)

on:
  release:
    types: [published]
env:
  OS: arm32v7
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1

    - name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${OS}

    - name: Update the Installed Docker Version
      run: sudo ${SCRIPTS}/01-update-docker.sh

    - name: Copy Build Dependencies
      run: ${SCRIPTS}/02-copy-build-dependencies.sh ${OS} ${{ GITHUB.WORKSPACE }}

    - name: Add Dependencies to the System PATH
      run: ${SCRIPTS}/03-export-path.sh ${OS} ${{ GITHUB.WORKSPACE }}

    - name: Build Config
      run: cd ${{ GITHUB.WORKSPACE }} && ./autogen.sh

    - name: Configure Build
      run: ${SCRIPTS}/04-configure-build.sh ${OS} ${{ GITHUB.WORKSPACE }} true

    - name: Build Raven
      run: make -j2

    - name: Package Up the Build
      run: ${SCRIPTS}/05-package.sh ${OS} ${{ GITHUB.WORKSPACE }} ${{ GITHUB.BASE_REF }}

    - name: Upload Build to the Nightly Site
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: "${{ GITHUB.WORKSPACE }}/release/"
        DEST_DIR: 'dev-builds/seed/arm/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker Container and Upload to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: ravenproject/ravend
        tag: arm32v7-latest
        registry: docker.io
        dockerfile: Dockerfile.arm32v7
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Upload Artifacts to Job
      uses: actions/upload-artifact@master
      with:
        name: raven-arm-linux-seed
        path: ${{ GITHUB.WORKSPACE }}/release
